### ISSUE TITLE
Add volume function support

### ISSUE THREAD

**Issue by ChrisFeline** [adrenak/GPUVideoPlayer#11]
It would be very helpful if it didn't blasted my ears. <3

**Comment by adrenak** [comment]
The audio is not played by Unity, but I think it uses a Windows API. System volume will be apply to it. I'll have a look sometime but I don't expect to be able to find a solution.

**Comment by adrenak** [comment]
Hi @ChrisFeline , I don't think there is a solution for this. The sound is played by the system and not a Unity AudioSource or anything like that. If you do want to control the audio from in-app controls, I think the best way would be to change the system volume itself from C#?
