### ISSUE TITLE
Playing video in original resolution

### ISSUE THREAD

**Issue by milos12345** [adrenak/GPUVideoPlayer#14]
I have tried playing 5K video but the played video is rendered at lower resolution.
If I play the provided Demo, and then use Scene view to come close to the texture, I can see that it does not play at the 5K. 
I have also tried setting it on another object with `GetComponent<Renderer>().material.SetTexture("_mainTexture", player.MediaTexture);` with the same result. Is it possible to play video in original resolution?

**Comment by adrenak** [comment]
Hi @milos12345 I'm unable to fix most bugs as the native code isn't written be me, but this has not happened before, do you have a repo I can clone and see?

**Comment by milos12345** [comment]
Hi @adrenak I'm sorry but now I am not able to reproduce this issue neither with the shipped demo scene or the quick code I did, but I have lost the video that I used for testing back then. I tested it afterwards with custom made 8K video with lines 1px apart and it was clearly displaying all the pixels, no down-sampling. If I find a way to reproduce it I will reopen it with more info. Thank you
