### ISSUE TITLE
cant SetPlaybackRate to video

### ISSUE THREAD

**Issue by fingerx** [adrenak/GPUVideoPlayer#5]
Hi,thanks for this. i want to set my video playbackrate but cant. can you add fucntion. thanks very much.

**Comment by fingerx** [comment]
Create a project manually and add
HRESULT CMediaPlayerPlayback::SetPlaybackRate(DOUBLE rate)
{
Log(Log_Level_Info, L"CMediaPlayerPlayback::SetPlaybackRate()");
If (nullptr != m_mediaPlaybackSession)
{
m_mediaPlaybackSession->put_PlaybackRate(rate);
}

Return S_OK;
}

All is ok.

**Comment by fingerx** [comment]
build is ok but unity show error cant find dll

**Comment by fingerx** [comment]
using win10 10.0.15063.0 sdk and universal windows dll

**Comment by fingerx** [comment]
using dependencyWalker show many dll not found. i dont konw why. need your help. thanks

![image](https://user-images.githubusercontent.com/5524551/50861994-5a922600-13d5-11e9-93d2-076f21461630.png)

**Comment by fingerx** [comment]
using dependencyWalker open your mediaplayback.dll show many dll miss but untiy is ok and play video is ok..

**Comment by fingerx** [comment]
using  c++ windows desktop dll fixed my error. this my mistake. sorry.

**Comment by spaul13** [comment]
@fingerx , can u please briefly tell me how u compiled the native scripts on windows? what compiler u used and what commands?
